### ISSUE TITLE
Merging a node with its parent's parent has weird behavior

### ISSUE THREAD

**Issue by alfongj** [gambitproject/jsgte#46]
(May be related with #44 #45)
Steps to reproduce:
1. Create tree with three nodes in a row
2. Try merging the bottom-most with the root
![image](https://cloud.githubusercontent.com/assets/822670/10569508/c054f756-75db-11e5-8744-06831bde644a.png)

**Comment by hvk3** [comment]
Since this issue has been resolved, wouldn't it be prudent to close it?

**Comment by stengel** [comment]
The game tree with 3 nodes now says "Cannot merge information set, please select nodes that do not share a path from the root" but subsequently freezes with green colors of clicked nodes and is in an incorrect state. So the post-handling of this error is still faulty.
